# Generated by Django 6.0.6 on 2026-07-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="officers",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
