# Generated by Django 6.0.6 on 2026-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyst",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="officer",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
